### ISSUE TITLE
Is there a way to add a logo or image in the center of the generated QR Code?

### ISSUE THREAD

**Issue by cosmin-novac** [panter/meteor-qrcode#3]
I noticed the linked larsjung library offers these options: https://larsjung.de/jquery-qrcode/

Does this meteor library implement them?

**Comment by cosmin-novac** [comment]
Nevermind, I figured it out. They all work and it's as easy as setting the size or the text parameters as shown in the example. 
Thanks for a great package!

**Comment by macrozone** [comment]
@tenshis hi, cool you figured out!

sorry, this package is ancient and i haven't neither used it nor maintained it for ages :-o
